### ISSUE TITLE
Compiler 5.6 68000 internal issue with optimizations arguments

### ISSUE THREAD

**Issue by djipi** [hth313/Calypsi-tool-chains#48] opened 2024-11-03 19:52 UTC
When compiling with --speed -O2 arguments, got the following problem.
internal error: Translator\Compiler\IL\Variable.hs:(102,1)-(103,51): Non-exhaustive patterns in function lookupVariable

The error will occur with only -O2 too.
The work around to avoid the error, it is to use only --speed

**Comment by hth313** [comment] 2024-11-04 16:55
Can you provide a source example with command line options?

**Comment by djipi** [comment] 2024-11-04 19:03
This is the line options, but I need time to narrow the problem in the source.
- --core=68000 --data-model --speed -O2 -c Far-Only
- --core=68000 --data-model -O2 -c Far-Only

**Comment by hth313** [comment] 2024-11-08 04:33
I have fixed this issue for the next release that is not so far away.

The problem is in the inliner if it encounters a function with a single `return` statement that contains a reference to a static variable that is not otherwise used in the function it is inlined in. Which is exactly what you have in the example.

You can temporarily use `--no-inline` to disable the inliner or lower optimization level.

**Comment by hth313** [comment] 2024-11-10 19:22
Fixed in release 5.7

**Closed by hth313** 2024-11-10 19:22 UTC
